# Generated by Django 2.1.2 on 2018-10-15 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181015_0733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucketlist',
            old_name='list_owner',
            new_name='owner',
        ),
    ]
