# Generated by Django 2.1.2 on 2018-10-15 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20181015_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucketlist',
            name='owner',
        ),
    ]
